### ISSUE TITLE
Consider adding a streaming toggle

### ISSUE THREAD

**Issue by Chill3dOut** [muesli/obs-cli#15]
First of all, thank you for a great tool. I've recently discovered it and is the only way I've found so far to control OBS using a Stream Deck in a pure Wayland session.

Following the recent changes I see there wasn't a streaming toggle, which I think would be a great addition and trivial (I guess?) to implement.

**Comment by muesli** [comment]
It's not quite as trivial as it seems at first, but I'll look into it: we'll probably manually need to check the current streaming state and then invert that.

Since I'm also the author of [deckmaster](https://github.com/muesli/deckmaster), I'm rather curious: which software do you currently use it with?

**Comment by Chill3dOut** [comment]
Thank you for looking into that. It is a great tool in its current state anyway.

I started out testing [streamdeck-ui](https://github.com/timothycrosley/streamdeck-ui/) and currently testing [streamdeckfs](https://github.com/twidi/streamdeckfs). I use Arch and didn't know about deckmaster tbh, will give it a try.

P.S. Now I know why deckmaster never showed up in my search results. I had to search for "stream deck" in AUR instead of "streamdeck"

**Comment by kaihendry** [comment]
As a https://dwm.suckless.org/ user, I did notice that obs has some "systray" panel implementations to toggle {Start,Stop} streaming. I was probably going to use this going forward, though I'm not sure which one sucks less.

**Comment by muesli** [comment]
> P.S. Now I know why deckmaster never showed up in my search results. I had to search for "stream deck" in AUR instead of "streamdeck"

Oh, that's interesting, thank you for bringing that up. It never occurred to me as the logo on the device itself reads "STREAM DECK", but I've just added an extra GitHub tag reading "streamdeck" to the project, which hopefully increases discoverability of the project a bit.

**Comment by muesli** [comment]
Ok, turns out the new API wrapper made this a lot easier! Thanks for creating the ticket!

**Comment by Chill3dOut** [comment]
Great news! :)
