### ISSUE TITLE
panic: idk what kinda message this is lol

### ISSUE THREAD

**Issue by larsks** [muesli/obs-cli#19]
I get this when trying to switch to a scene:

```
$ obs-cli  --password "secret" scene switch "Webcam"
panic: idk what kinda message this is lol

goroutine 23 [running]:
github.com/andreykaipov/goobs.(*Client).handleRawMessages(0xc000142d20, 0xc000206000, 0xc000206060)
        github.com/andreykaipov/goobs@v0.6.0/client.go:180 +0x405
github.com/andreykaipov/goobs.(*Client).handleMessages(0xc000142d20)
        github.com/andreykaipov/goobs@v0.6.0/client.go:124 +0xe7
created by github.com/andreykaipov/goobs.New
        github.com/andreykaipov/goobs@v0.6.0/client.go:72 +0x172

```

This is with:

- `obs-cli-0.2.0-1.x86_64`
- `obs-studio-27.0.1-2.fc34.x86_64`

**Comment by larsks** [comment]
Ah, I see this is version skew; I inadvertently grabbed the 5.0.0 pre-release of obs-websocket.

**Comment by muesli** [comment]
Thanks for the report. Ideally this still shouldn't crash, of course. I'll forward this report to the upstream goobs project.

**Comment by muesli** [comment]
Pinging @andreykaipov.

**Comment by andreykaipov** [comment]
Aha that's embarrassing! 😅 Thanks for letting me know 

Yeah since v5.x is so different, my client library failed recognizing the message type. Sorry for the confusion. I'll definitely improve that error! Pretty sure I can handle it gracefully
