### ISSUE TITLE
sceneitem not working

### ISSUE THREAD

**Issue by oparada1988** [muesli/obs-cli#21]
When  I attempt to use the sceneitem command I get an error. I first use the "list" flag and it doenst show any of the sources, and useing the toggle gives me the error of "Error: Got error from OBS executing request "GetSceneItemProperties": requested scene doesn't exist
"

$ obs-cli sceneitem list Game Scene
$ obs-cli sceneitem toggle Game Scene you_suck.mov
Error: Got error from OBS executing request "GetSceneItemProperties": requested scene doesn't exist
Usage:
  obs-cli sceneitem toggle [flags]

Flags:
  -h, --help   help for toggle

Global Flags:
      --host string       host to connect to (default "localhost")
      --password string   password for connection
  -p, --port uint32       port to connect to (default 4444)

Got error from OBS executing request "GetSceneItemProperties": requested scene doesn't exist

![Screenshot from 2021-11-19 23-44-38](https://user-images.githubusercontent.com/4031078/142714760-02a6c0a6-c922-439a-8908-56e2cc1c740f.png)

![Screenshot from 2021-11-19 23-44-53](https://user-images.githubusercontent.com/4031078/142714816-4661f70c-a981-4945-b2ef-e83ca1351791.png)

**Comment by muesli** [comment]
Try putting `Game Scene` in quotes, like:

```bash
obs-cli sceneitem list "Game Scene"
```

**Comment by oparada1988** [comment]
> Try putting `Game Scene` in quotes, like:
> 
> ```shell
> obs-cli sceneitem list "Game Scene"
> ```

Thank you for the clarification, this issue can be closed!

**Comment by muesli** [comment]
Thanks for confirming!
