### ISSUE TITLE
I created a similar tool

### ISSUE THREAD

**Issue by leafac** [muesli/obs-cli#3]
Thanks for creating this. I’ve created a similar tool that I also called [obs-cli](https://github.com/leafac/obs-cli). The main differences are: 1. It’s written in Node.js instead of Go; and 2. It [supports authentication](https://github.com/muesli/obs-cli/issues/2) and seems to support a wider variety of requests (everything that obs-websocket itself provides).

I linked to your tool in the README for mine.

**Comment by Ashark** [comment]
Thank you! Yes, your variant of utility has ability to make request that this one does not allow.
