### ISSUE TITLE
sceneitem show, hide and toggle also always unlock the source

### ISSUE THREAD

**Issue by flexiondotorg** [muesli/obs-cli#34]
## Expected behaviour

Showing, hiding or toggling a source via `obs-cli sceneitem` should only change the source visibility.

## Actual behaviour

Showing, hiding or toggling a source via `obs-cli sceneitem` also always unlocks the given source, in addition to changing the source visibility.

I'm using `obs-cli` v0.3.0 for Linux (amd64) from this projects releases.

**Comment by muesli** [comment]
Thanks @flexiondotorg! Fixed in v0.3.1.
