### ISSUE TITLE
replaybuffer command missing on windows version

### ISSUE THREAD

**Issue by d0vere** [muesli/obs-cli#47]
like title
![Immagine 2022-01-04 220339](https://user-images.githubusercontent.com/97129466/148123680-48d5e299-4d89-4ac4-bcf9-0d778794fe83.png)

**Comment by muesli** [comment]
Sorry, the `replaybuffer` command hasn't been part of a stable release yet. It's the only change after v0.4.0 (as of now) and will be part of an upcoming v0.5.0.

**Comment by d0vere** [comment]
Sorry didnt see, thanks for the fast reply

**Comment by muesli** [comment]
> Sorry didnt see, thanks for the fast reply

No worries, it's confusing and I really can't blame you. In general it makes sense to look at the README of the version you're actually running, but myself I tend to just look at `main` / `master` as well :smile:

I'll try to release a v0.5.0 really soon, so you get to play with that feature. I'll close this ticket after the release, so you get notified as soon as it's available!

**Comment by muesli** [comment]
Alright, v0.5.0 is out, you should be able to use this on Windows now!
