### ISSUE TITLE
How to know the output file name to make it scriptable?

### ISSUE THREAD

**Issue by kaihendry** [muesli/obs-cli#6]
I'm looking to [ditch my ffmpeg](https://github.com/kaihendry/recordmydesktop2.0/blob/master/x11capture) script which irritatingly kept going slightly out of sync with my audio. _obs-cli_ appears like my [best chance at making linux screencasting scriptable](https://obsproject.com/forum/threads/how-do-i-know-im-recording.143454/) from dmenu. And ideally I have some simple way to show that I am recording from my [status bar](https://github.com/kaihendry/dotfiles/blob/master/bin/dwm_status).

{start,stop}-recording [works](https://s.natalian.org/2021-05-10/2021-05-10_09-05-23.mp4), though I am curious if I can get the output filename so I can then [upload](https://github.com/kaihendry/dotfiles/blob/master/bin/upload) the video for quick sharing.

**Comment by muesli** [comment]
There's a `recording-status` which has recently been added to OBS's API (4.9.0), which could solve this. Sadly the go bindings aren't up-to-date yet (supporting 4.7.0 currently).

**Comment by muesli** [comment]
Good news, everyone! There's a `obs-cli recording status` command now, that displays the filename and timecode amongst other things.
