### ISSUE TITLE
Few Options not working

### ISSUE THREAD

**Issue by HeHateToCode** [muesli/obs-cli#7]
Why theres no more support for  `obs-cli start-recording,obs-cli stop-recording,obs-cli toggle-recording`.
These options were mentioned in `README.MD` but cant find them in the tool.

**Comment by muesli** [comment]
I'm afraid this has been broken since a recent API update. I'll probably have to switch to a different OBS client library altogether.

**Comment by HeHateToCode** [comment]
> I'll probably have to switch to a different OBS client library altogether.

Damn thats hard switching to a new library

**Comment by muesli** [comment]
Migration to goobs is complete and this should be fixed now.
